import React from 'react'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from 'react-bootstrap';
import './Navbar.css';
function BilgiAlani() {
  return (
    <div>
      <Container>
        <hr className="width-line" />
        <div className='container'>
          <Container>
            <h4>Kadınlara Özel Yeni Ürünler Uygun Fiyatlarla Trendyol’da!</h4>
            <p style={{ fontWeight: '300' }}>Üretilen giyim parçalar sayesinde şık ve göz alıcı bir tarza sahip olmak mümkündür. Kadın elbise modelleri birbirinden şık tasarımlarıyla ön plana çıkarlar. Sezonun trend renkleri kullanılarak tasarlanan elbise çeşitleri farklı kombin seçenekleri sunar. Sade, çiçekli, uzun, mini, çok renkli, fırfırlı, düğmeli, şifon ve örme tasarımlara imza atılır. Kadın tesettür elbise başlığı altında ayrı bir ürün grubu oluşturulur. Ölçülü giyinmek isteyen kitleye hitap edilir. Tesettür elbise modelleri geniş bir yelpaze oluştur. Hazırlanan parçalar farklı kombinlerde rahatlıkla kullanılır. Tesettür abiye modelleri şık görünmek istenilen zamanların öncelikli tercihi olur. Klasik giyim tarzı için topuklu ayakkabı tercih edilir. Rahatlığından ödün vermek istemeyenler ise seçimlerini sneaker modlelerinden yana kullanırlar. Kadın kot pantolon modelleri arasında yüksek bel, bol paça, yırtmaçlı, açık mavi, düğme detaylı ve kargo cepli tasarımlar dikkat çeker. Yazın sneaker ile kombinlenen bu parçalar, kışın da kadın bot modelleri ile tercih edilebilir. Kadın spor ayakkabı ile yaz ve kış stilinizi rahatlıkla oluşturabilirsiniz.</p>
            <h5>Şık ve Kaliteli Kadın Sweatshirt Modelleri</h5>
            <p style={{ fontWeight: '300' }}>Kadın sweatshirt modeli şık ve rahat olmasıyla her mevsim kombinleri tamamlar. Ürünler kapüşonlu, fermuarlı, örme, yırtmaç detaylı, dijital baskılı modeller de bisiklet yaka, dik yaka ve yüksek yaka tasarımlarıyla öne çıkar. Kadın kazak modelleri ile klasik ve spor tarzınızı tamamlayabilirsiniz. Üst giyim parçaları kadın pantolon tasarımlarıyla bir araya getirilir. Yapılan kombinler mevsimlere göre değişiklik gösterir. Yaz koleksiyonunun önemli parçasını oluşturan kadın tişört çeşitleri V yaka, bisiklet yaka, yuvarlak yaka ve dik yaka modelleriyle beğeni toplar. Mevcut tasarımlar sade ve renkli çizgilerin yanı sıra boyfriend baskılı, yırtmaçlı, örme, anne kız kombini, fırfır detaylı ve kolsuz olarak da gruplandırılır. Bol kesim, boyfriend, koşu tişörtü, desenli ve sportif modeller günlük giyim için tercih edilir. Özel davetlerde kullanılmak üzere satın alınan parçalar kadın ceket seçenekleriyle kombinlenir. Ceketleri kadın bluz modellerinde de tamamlayıcı unsur olarak kullanabilirsiniz. Dilerseniz de kadın gömlek çeşitlerinden birini seçerek klasik bir hava yakalayabilirsiniz.</p>
            <h5>Göz Alıcı Kadın Saat Seçenekleri</h5>
            <p style={{ fontWeight: '300' }}>Kıyafetlerin tamamlayıcı unsuru kadın saat modelleri kordon materyaline, kordon rengine, kasa rengine, kasa çapına, kasa materyaline, su geçirmezlik özelliğine ve kadran şekline göre değişiklik gösterir. Kadın kolye çeşitleri de kıyafetleri şık gösteren aksesuarların başında gelir. Bijuteri, gümüş, çelik, altın, inci ve pırlanta modeller hem günlük hem de özel zamanlarda yapılan kombinleri tamamlar. Etkileyici tasarıma sahip kadın çanta modellerini de kıyafetleriniz ile uyumlu şekilde kullanabilirsiniz. Kullanım yerine göre omuz çantasından el çantasına, sırt çantasında spor çantaya kadar pek çok farklı modeli renk seçenekleriyle bulabilirsiniz. Yaz aylarının olmazsa olmaz aksesuarı ise kadın gözlük seçenekleridir. Ürünler güneş ışınlarının zararlı etkisinden korunmaya destek olurlar. Model seçiminde cam rengi, çerçeve formu, çerçeve rengi, materyal, çerçeve tipi, cam tipi ve fiyat belirleyici rol oynayan kriterlerdir. Hem aksesuar hem de kadın giyim parçalarını Trendyol indirimlerinden faydalanarak satın alabilirsiniz.</p>
            <h5>Beğenilen Büyük Beden Kadın Ürünleri</h5>
            <p style={{ fontWeight: '300' }}>Büyük beden kadın giyimi farklı ürün çeşitlerini bünyesinde barındırır. Elbiseden eteğe, bluzdan tişörte kadar pek farklı alternatif bulunur. Öne çıkan kadın hırka modelleri kış ayları için birer kurtarıcı görevi görür. Markaların ürün çeşitlerinde fermuarlı, cep detaylı, mevsimlik, örme kumaş, desenli, renkli ve sade tasarıma yer verilir. Kadın kaban çeşitleri kapitoneli, taş detaylı, kürk görünümlü, dökümlü, kemerli, ve düğmeli kruvaze örme modelleri ile kış aylarında kombinlerin tamamlayıcısıdır. Kadın mont modelleri mevsimine uygun su ve rüzgar geçirmez özelliklere sahiptir. Trençkot tasarımı ise genellikle mevsim geçişlerinde kullanılmak üzere satın alınır. Dış giyim parçalarının yanı sıra ev giyim parçaları da ilgiyle takip edilir. Kadın pijama takımı puantiyeli, fırfırlı, dantel işlemeli, düğmeli, baskılı modelleriyle ön plana çıkar. Üretim aşamasında farklı kumaş ve kalıp tercihleri yapılır. Ürünlerin ortak özellikleri ise sahip oldukları rahatlıktır. Kadın gecelik modelleri de rahat kumaş yapısı ve şık tasarımıyla müşterilerin beğenisini kazanır. Sade tasarımlar yanı sıra fırfırlı, nakışlı, işlemeli modeller de tercih edilebilir.</p>
            <h5>Kombinlere Şıklık Katan Kadın Ayakkabı Modelleri</h5>
            <p style={{ fontWeight: '300' }}>Kıyafetlerin tamamlayıcı unsuru ayakkabılar kullanıldığı yere göre değişiklik gösterir. Sporu hayatına entegre eden kişiler hafif ve rahat kadın koşu ayakkabısı sabah koşularını yapabilir. Kadın eşofman yüksek bel, lastikli, penye, yazlık, mevsimlik, bol paça, büyük beden ve cep detaylı tasarımları ile dikkat çeker. Eşofman takımlarınızı kadın ayakkabı modelleriyle tamamlayabilirsiniz. Kadın ev botu esnek ve ses yapmayan PVC tabana sahiptir. Ayakları sıcak tutar. Kadın sandalet modelleri yüksek taban, düz taban, çıtçıtlı, bağlamalı, büzgü detaylı, şeritli, renkli, anatomik ve parmak arası tasarımları ile öne çıkar. Günlük kullanım için rahat tabanlı deri kadın babet tercih edilebilir. Boyun olduğundan uzun görünmesi için ise model seçimi topuklu ayakkabı tasarımından yana kullanılabilir. Topuk boyu ürünlere göre değişiklik gösterir. Ayrıca giydiğiniz ayakkabının türüne göre görünmez, yarım ve dikişsiz kadın çorap çeşitlerini deneyebilirsiniz. İç giyim ürünleri de kadın giyiminin önemli parçasını oluşturur. Kıyafetleri kusursuz gösteren toparlayıcı sütyen dantel detayları ve ayarlanabilir askıları ile şıklığından ödün vermek istemeyenlerin birinci tercihi olur. Balenli ve dolgulu sütyen takımı farklı renk alternatifleriyle satılır. Bralet iç giyim kategorisinin öne çıkan parçalarından bir diğeridir. Kullanışlı tasarımı sayesinde öncelikli tercihler arasında yer alır. Kadın bornoz model kategorisini oluşturan çeşitli modeller bulunur. Set halinde satılan ürünlerin içerisinde pamuklu, desenli, sade kadın ve erkek bornoz, 2 tane havlu ve 2 tane baş havlusu vardır. Kadın mayo çeşitleri askılı, yüksek bel, şortlu, desenli, dekolteli, büzgü detaylı tasarımlarıyla tatilde de şık ve rahat olmanızı sağlar. Trendyol’daki mevcut modeller arasından zevkinize ve ihtiyacınıza uygun olanı satın alabilirsiniz.</p>
            <h5>En Yeni Ürünlerle İlginizi Çekebilecek Kategoriler</h5>
            <p style={{ fontWeight: '300', marginBottom:'30px'}}>Spor Ayakkabı | Ferace | Tesettür Takım | Etek | Tesettür Tunik | Çanta | Uzun Elbise | Sırt Çantası | Toparlayıcı Sütyen | Tesettür Etek | Tesettür Mont | Deri Etek | Terlik | Kot Etek | Tesettür Hırka | Korse Tayt | Saten Etek | Mini Abiye | Tesettür Yelek | Dekolteli Elbise</p>
          </Container>
        </div>
      </Container>
    </div>


  )
}

export default BilgiAlani
